name: $(date:yyyyMMdd)$(rev:.r)

schedules:
- cron: "0 0 1 * *"
  displayName: Run At 00:00 on day-of-month 1
  branches:
    include:
    - main

trigger:
- main

resources:
- repo: self

parameters:
- name: JMETER_VERSION
  displayName: jmeter-base Version
  type: string
  default: '5.0'

variables:
  tag: '$(Build.BuildNumber)'
  version: ${{parameters.JMETER_VERSION}}

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'spy86/jmeter-base'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
        arguments: '--build-arg JMETER_VERSION=$(version)'
    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'spy86/jmeter-base'
        command: 'push'
        tags: '$(tag)'

- stage: Build_Latest_tag
  dependsOn: [Build]
  displayName: Rebuild an latest image
  jobs:
  - job: Build_latest_tag
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'spy86/jmeter-base'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'
        arguments: '--build-arg JMETER_VERSION=$(version)'
    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'spy86/jmeter-base'
        command: 'push'
        tags: 'latest'